### ISSUE TITLE
how to use it for rhel 6?

### ISSUE THREAD

**Issue by maraev** [helvalius/nominatim-docker#1]
Thanx for it. Can I use this for RHEL 6? Or it is just useful for Ubuntu

**Comment by helvalius** [comment]
I have used Ubuntu in the Dockerfile as base image. You can use this of course in a Red Hat host system as long as you have Docker installed. 
Do you need to have Nominatim run in a RH environment?

**Comment by maraev** [comment]
yes, but I'm quite new in dockers

**Comment by helvalius** [comment]
If you are only interested in running Nominatim with this docker you can pull the docker image from docker hub (https://registry.hub.docker.com/u/helvalius/nominatim-docker-development):

docker pull helvalius/nominatim-docker-development

Then run this docker image as a container. Be aware that this image only contains monaco as I'm using this for testing purposes. Im working on changing it to read a pbf from a volume to be flexible.
