### ISSUE TITLE
Nominatim has moved from automake to cmake

### ISSUE THREAD

**Issue by awakse** [helvalius/nominatim-docker#12]
Great project for getting things up and running quickly!
I got this error message when running `docker build -t nomination .`

```
Step 24 : RUN ./autogen.sh
 ---> Running in 8331e56df6ed
/bin/sh: 1: ./autogen.sh: not found
The command '/bin/sh -c ./autogen.sh' returned a non-zero code: 127
```

This is because Nominatim has moved from automake to cmake in their git repos.

I changed from `git clone` and instead used wget to get the 2.5.0 tar release instead. Perhaps you wanna update your Dockerfile with either that, or change to cmake.

Thanks!

**Comment by helvalius** [comment]
@awakse  Thanks for the heads up! I want to create to repositories in the next week, one for the latest release and one for the latest head. Then I'll change the latest one to cmake.
