### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ruxandra-valcu** [helvalius/nominatim-docker#6]
Trying to build fails on step 33 (RUN service postgresql start &&   sudo -u nominatim ./utils/setup.php --osm-file /app/data.pbf --all --threads 2) with the following error:

PHP Fatal error:  Call to undefined method DB_Error::PEAR_Error() in /usr/share/php/DB.php on line 966

**Comment by helvalius** [comment]
Can't reproduce with current version
